name: Build

on:
  push:
  pull_request:

jobs:
  macos-build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build iSnap
        run: |
          xcodebuild \
            -project iSnap.xcodeproj \
            -scheme iSnap \
            -configuration Debug \
            -derivedDataPath .build \
            CODE_SIGNING_ALLOWED=NO \
            build

